"""Initial migration

Revision ID: 12797a709c4f
Revises: 
Create Date: 2026-04-03 21:53:14.177721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12797a709c4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index('idx_users_role', 'users', ['role_id'], unique=False)
    op.create_table('search_phrases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phrase')
    )
    op.create_index('idx_search_phrases_user', 'search_phrases', ['user_id'], unique=False)
    op.create_table('dynamics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='Идентификатор группы (повторяется для одного логического запроса с несколькими фразами)'),
    sa.Column('search_phrase_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('device1_id', sa.Integer(), nullable=True),
    sa.Column('device2_id', sa.Integer(), nullable=True),
    sa.Column('device3_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device1_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['device2_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['device3_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['search_phrase_id'], ['search_phrases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dynamics_device1', 'dynamics', ['device1_id'], unique=False)
    op.create_index('idx_dynamics_device2', 'dynamics', ['device2_id'], unique=False)
    op.create_index('idx_dynamics_device3', 'dynamics', ['device3_id'], unique=False)
    op.create_index('idx_dynamics_group', 'dynamics', ['group_id'], unique=False)
    op.create_index('idx_dynamics_region', 'dynamics', ['region_id'], unique=False)
    op.create_index('idx_dynamics_search_phrase', 'dynamics', ['search_phrase_id'], unique=False)
    op.create_index('idx_dynamics_user', 'dynamics', ['user_id'], unique=False)
    op.create_table('regions_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='Идентификатор группы (повторяется для одного логического запроса с несколькими фразами)'),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('search_phrase_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('region_type', sa.String(length=50), nullable=True, comment='Тип региона (например, "country", "city")'),
    sa.Column('device1_id', sa.Integer(), nullable=True),
    sa.Column('device2_id', sa.Integer(), nullable=True),
    sa.Column('device3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device1_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['device2_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['device3_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['search_phrase_id'], ['search_phrases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regions_requests_device1', 'regions_requests', ['device1_id'], unique=False)
    op.create_index('idx_regions_requests_device2', 'regions_requests', ['device2_id'], unique=False)
    op.create_index('idx_regions_requests_device3', 'regions_requests', ['device3_id'], unique=False)
    op.create_index('idx_regions_requests_group', 'regions_requests', ['group_id'], unique=False)
    op.create_index('idx_regions_requests_search_phrase', 'regions_requests', ['search_phrase_id'], unique=False)
    op.create_index('idx_regions_requests_user', 'regions_requests', ['user_id'], unique=False)
    op.create_table('top_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False, comment='Идентификатор группы'),
    sa.Column('search_phrase_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('device1_id', sa.Integer(), nullable=True),
    sa.Column('device2_id', sa.Integer(), nullable=True),
    sa.Column('device3_id', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device1_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['device2_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['device3_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['search_phrase_id'], ['search_phrases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_top_requests_device1', 'top_requests', ['device1_id'], unique=False)
    op.create_index('idx_top_requests_device2', 'top_requests', ['device2_id'], unique=False)
    op.create_index('idx_top_requests_device3', 'top_requests', ['device3_id'], unique=False)
    op.create_index('idx_top_requests_group', 'top_requests', ['group_id'], unique=False)
    op.create_index('idx_top_requests_region', 'top_requests', ['region_id'], unique=False)
    op.create_index('idx_top_requests_search_phrase', 'top_requests', ['search_phrase_id'], unique=False)
    op.create_index('idx_top_requests_user', 'top_requests', ['user_id'], unique=False)
    op.create_table('dynamics_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dynamics_id', sa.Integer(), nullable=False),
    sa.Column('search_phrase_id', sa.Integer(), nullable=True, comment='Связанная фраза (если нужна дополнительная привязка)'),
    sa.Column('point_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('share', sa.Float(), nullable=False),
    sa.CheckConstraint('count >= 0'),
    sa.CheckConstraint('share BETWEEN 0 AND 1'),
    sa.ForeignKeyConstraint(['dynamics_id'], ['dynamics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_phrase_id'], ['search_phrases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dynamics_points_dynamics', 'dynamics_points', ['dynamics_id'], unique=False)
    op.create_index('idx_dynamics_points_search_phrase', 'dynamics_points', ['search_phrase_id'], unique=False)
    op.create_table('regions_requests_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regions_requests_id', sa.Integer(), nullable=False),
    sa.Column('search_phrase_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('share', sa.Float(), nullable=False),
    sa.Column('affinity_index', sa.Float(), nullable=True),
    sa.CheckConstraint('count >= 0'),
    sa.CheckConstraint('share BETWEEN 0 AND 1'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['regions_requests_id'], ['regions_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_phrase_id'], ['search_phrases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regions_requests_items_region', 'regions_requests_items', ['region_id'], unique=False)
    op.create_index('idx_regions_requests_items_request', 'regions_requests_items', ['regions_requests_id'], unique=False)
    op.create_index('idx_regions_requests_items_search_phrase', 'regions_requests_items', ['search_phrase_id'], unique=False)
    op.create_table('top_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_request_id', sa.Integer(), nullable=False),
    sa.Column('search_phrase_id', sa.Integer(), nullable=True, comment='Связанная фраза (если присутствует в справочнике)'),
    sa.Column('phrase', sa.Text(), nullable=False, comment='Текст фразы (денормализовано для быстрого доступа)'),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.CheckConstraint('count > 0'),
    sa.ForeignKeyConstraint(['search_phrase_id'], ['search_phrases.id'], ),
    sa.ForeignKeyConstraint(['top_request_id'], ['top_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_top_request_items_search_phrase', 'top_request_items', ['search_phrase_id'], unique=False)
    op.create_index('idx_top_request_items_top_request', 'top_request_items', ['top_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_top_request_items_top_request', table_name='top_request_items')
    op.drop_index('idx_top_request_items_search_phrase', table_name='top_request_items')
    op.drop_table('top_request_items')
    op.drop_index('idx_regions_requests_items_search_phrase', table_name='regions_requests_items')
    op.drop_index('idx_regions_requests_items_request', table_name='regions_requests_items')
    op.drop_index('idx_regions_requests_items_region', table_name='regions_requests_items')
    op.drop_table('regions_requests_items')
    op.drop_index('idx_dynamics_points_search_phrase', table_name='dynamics_points')
    op.drop_index('idx_dynamics_points_dynamics', table_name='dynamics_points')
    op.drop_table('dynamics_points')
    op.drop_index('idx_top_requests_user', table_name='top_requests')
    op.drop_index('idx_top_requests_search_phrase', table_name='top_requests')
    op.drop_index('idx_top_requests_region', table_name='top_requests')
    op.drop_index('idx_top_requests_group', table_name='top_requests')
    op.drop_index('idx_top_requests_device3', table_name='top_requests')
    op.drop_index('idx_top_requests_device2', table_name='top_requests')
    op.drop_index('idx_top_requests_device1', table_name='top_requests')
    op.drop_table('top_requests')
    op.drop_index('idx_regions_requests_user', table_name='regions_requests')
    op.drop_index('idx_regions_requests_search_phrase', table_name='regions_requests')
    op.drop_index('idx_regions_requests_group', table_name='regions_requests')
    op.drop_index('idx_regions_requests_device3', table_name='regions_requests')
    op.drop_index('idx_regions_requests_device2', table_name='regions_requests')
    op.drop_index('idx_regions_requests_device1', table_name='regions_requests')
    op.drop_table('regions_requests')
    op.drop_index('idx_dynamics_user', table_name='dynamics')
    op.drop_index('idx_dynamics_search_phrase', table_name='dynamics')
    op.drop_index('idx_dynamics_region', table_name='dynamics')
    op.drop_index('idx_dynamics_group', table_name='dynamics')
    op.drop_index('idx_dynamics_device3', table_name='dynamics')
    op.drop_index('idx_dynamics_device2', table_name='dynamics')
    op.drop_index('idx_dynamics_device1', table_name='dynamics')
    op.drop_table('dynamics')
    op.drop_index('idx_search_phrases_user', table_name='search_phrases')
    op.drop_table('search_phrases')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('regions')
    op.drop_table('devices')
    # ### end Alembic commands ###
