"""add_m2m_regions

Revision ID: 2756e58a30fa
Revises: 12797a709c4f
Create Date: 2026-04-19 10:16:22.674233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2756e58a30fa'
down_revision: Union[str, None] = '12797a709c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('top_request_regions',
    sa.Column('top_request_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['top_request_id'], ['top_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('top_request_id', 'region_id')
    )
    op.drop_index('idx_top_requests_region', table_name='top_requests')
    op.drop_constraint('top_requests_region_id_fkey', 'top_requests', type_='foreignkey')
    op.drop_column('top_requests', 'region_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('top_requests', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('top_requests_region_id_fkey', 'top_requests', 'regions', ['region_id'], ['id'])
    op.create_index('idx_top_requests_region', 'top_requests', ['region_id'], unique=False)
    op.drop_table('top_request_regions')
    # ### end Alembic commands ###
