"""dynamics_m2m_regions_and_points_fix

Revision ID: 6c12934f1153
Revises: 2756e58a30fa
Create Date: 2026-04-19 12:40:40.310967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c12934f1153'
down_revision: Union[str, None] = '2756e58a30fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamics_regions',
    sa.Column('dynamics_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dynamics_id'], ['dynamics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dynamics_id', 'region_id')
    )
    op.drop_index('idx_dynamics_region', table_name='dynamics')
    op.drop_constraint('dynamics_region_id_fkey', 'dynamics', type_='foreignkey')
    op.drop_column('dynamics', 'region_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dynamics', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('dynamics_region_id_fkey', 'dynamics', 'regions', ['region_id'], ['id'])
    op.create_index('idx_dynamics_region', 'dynamics', ['region_id'], unique=False)
    op.drop_table('dynamics_regions')
    # ### end Alembic commands ###
